INSERT INTO notification (notification_id, target_id, message) VALUES
(1, 1, 'You have a new follower from the enchanted forest'),
(2, 2, 'Your magical post just got a new like'),
(3, 3, 'New comment on your craft'),
(4, 4, 'Your story has enchanted another reader'),
(5, 5, 'Dragon sightings reported near your last post'),
(6, 6, 'Battle cry appreciated by fellow orcs'),
(7, 7, 'Centaur race event invitation'),
(8, 8, 'Sirens have replied to your song'),
(9, 9, 'Your trick has been uncovered'),
(10, 10, 'New flowers bloom in your forest'),
(11, 11, 'Invitation to the vampire gathering'),
(12, 12, 'Your potion recipe has been featured'),
(13, 13, 'A goat tried to cross the bridge'),
(14, 14, 'Your phoenix tale has inspired many'),
(15, 15, 'Ancient scroll discoveries need your expertise'),
(16, 16, 'New depths have been explored'),
(17, 17, 'Griffin spotted near your location'),
(18, 18, 'Pearl diving contest awaits'),
(19, 19, 'Feast preparations are complete'),
(20, 20, 'Gold found at the end of the rainbow');
